# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
sudo: required

language: ruby

rvm:
  - 2.3

services:
  - docker

env:
  - TERRAFORM_VERSION=0.13.0 IMAGE_NAME=azure-network-module

jobs:
  include:
    - stage: build
      if: type = pull_request
      install: true
      script:
      - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} -t ${IMAGE_NAME} .
      - docker run ${IMAGE_NAME} rake build
    - stage: full
      if: type = push AND branch = master
      install: true
      script:
      - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t ${IMAGE_NAME} .
      - docker run ${IMAGE_NAME} rake full

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d <directory> --bc-api-key <055f59b2-833c-4ca9-a4a2-5f1b07d0a90b
>::<C0apEk/7J84/ewJjYP2cR1l7I9Q=> --repo-id <sparab1997
/
terraform-azurerm-network> --branch <branch>
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: <app.ind.prismacloud.io>